# Generated by Django 3.2.13 on 2024-08-08 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tax_include',
            new_name='tax_included',
        ),
    ]
